from package.Stack import *
def main():
	p = Stack()
	print(type(p))
	s = Push(p, 2)
	print(type(s))
	t = Push(s, 3)
	print(type(t))
	q = Push(p, 4)
	print(type(q))
	qui = Pop(t)
	print()
	print("Primeira: Value", p.pilha.value, "Depth", p.pilha.depth)
	print("Segunda: Value", s.pilha.value, "Depth", s.pilha.depth)
	print("Terceira: Value", t.pilha.value, "Depth", t.pilha.depth)
	print("Terceira->parent == Segunda: Value", t.pilha.parent.value, "Depth", t.pilha.parent.depth)
	print("Quarta: Value", q.pilha.value, "Depth", q.pilha.depth)
	print("Quarta->parent == Primeira: Value", q.pilha.parent.value, "Depth", q.pilha.parent.depth)
	print("----")
	print("Quinta == Segunda: Value", qui.pilha.value, "Depth", qui.pilha.depth)
	print("Quinta->parent == Primeira: Value", qui.pilha.parent.value, "Depth", qui.pilha.parent.depth)
main()